const tips=[
    "There are tons of easter eggs in CMD; Try to find them all",
    "Did you know Boston is also called Beantown? Just me? oh...",
    "I actually have a youtube! Please subscribe, I want to buy new cymbals for my drums but I have a bank balance of $-2.59",
    "Are you reading these?",
    "Ancient Greece used to elect public officials with beans! Another reason to love them",
    "Pythogoras hated beans. Stupid, robe wearing triangle guy; he doesn't have the right to an opinion",
    "Beans on toast are good, I don't care what you say",
    "British people are very scary",
    "run 'secret' in DOS; I dare you",
    "You know this project is open source? yeah, you can f**k it up in any way you want",
    "I spent 4 hours on this update please follow my socials",
    "Half the sh*t here is like an bean-themed aldi version of actual apps",
    "Tell your friends about Beansite! (I need money)",
    "Adsense rejected me :(",
    "pringles",
    "Lorem ipsum dolor sit amet",
    "Beans",
    "Hello, World!",
    "scrotum :P",
    "Sub to my yt pls",
    "balls",
    "Sorry about loading speeds, this project is HUGE!!",
    "beans beans beans. jessie ate some beans. he was happy, happy, happy that he ate some beans",
    "kurt cobian once wrote a song about beans (yes, he was sober)",
    "Hi",
    "Hola",
    "Fuck Google Adsense im switching to Adinplay",
    "Maybe ill get ads some day. if i do, i promise i wont spam. im not that greedy",
    "i think you should be in class, buddy",
    "skibidi",
    "skibidi toilet",
    "sigma alpha male",
    "skibidi toilet sigma alpha male livvy dunne and baby gronk fanum tax rizz ohio",
    "im slowly losing all braincells",
    "sometimes you need to close a door to open a window",
    "my brother said im on the spectrum",
    "dont call me selfish, i aint sharin",
    "this 60/40 isnt working. i want a 100 of your time. your mine",
    "remember, if yall wants game scroll to the bottom of BeanPowered I do requests yk",
    "js ask me for games and ill add em.",
    "WHAT THE FUCK IS A KILOMETER"
]